# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IJKMediaPlayerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IJKMediaPlayerDemo
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'SVProgressHUD'
  pod 'SDWebImage'

  target 'IJKMediaPlayerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IJKMediaPlayerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
